services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-net

  redis:
    image: redis:7-alpine
    ports:
      - "3000:6379"
    volumes:
      - redis_data:/data
    networks:
      - chat-net

  backend1:
    build: ./backend
    ports: ["8001:8001"]
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - chat-net
  backend2:
    build: ./backend
    ports: ["8002:8001"]
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - chat-net

  # proxy:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - backend1
  #     - backend2
  #   networks:
  #     - chat-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # depends_on:
    #   - proxy
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
